language: vim

before_script: |
  hg clone https://code.google.com/p/vim/
  cd vim
  ./configure --with-features=huge --enable-rubyinterp --enable-pythoninterp
  make
  sudo make install
  cd -

script: |
  /usr/local/bin/vim -Nu <(cat << VIMRC
  filetype off
  set rtp+=.
  filetype plugin indent on
  syntax enable
  VIMRC) -c 'Vader! test/*' > /dev/null
